import { NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { ClientToaster } from "@/components/ui/ClientToaster";
import Header from "@/components/globals/Header";
import Footer from "@/components/globals/Footer";
import "../globals.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { cookies } from "next/headers";
import NotificationsProvider from "@/libs/providers/NotificationsProvider";

export const metadata: Metadata = {
  // change the icon to the global icon
  icons: {
    icon: "/image0.png",
  },
  title: "Smart Moving",
  description: "Generated by Smart Moving",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  type Locale = "dk" | "en" | "ar";
  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }
  const messages = await getMessages({ locale });

  const token = (await cookies()).get("token")?.value;



  return (
    <html dir={locale === "ar" ? "rtl" : "ltr"} lang={locale}>
      <body>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <NotificationsProvider token={token} />
          <ClientToaster />
          <Header />
          <main className="bg-[#192953] min-h-screen border-b-0 pb-[50px]">
            {children}
          </main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
